### ISSUE TITLE
Menus doesn't in phone mode

### ISSUE THREAD

**Issue by bjornbak** [TheCoder4eu/BootsFaces#12]
Interesting project - exactly what I've been looking for!

But browsing around on www.bootsfaces.net it turns out the menus doesn't work in phone mode. When I press the "burger" button it gets a pressed look but nothing happens.

Tested in desktop + Android chromes.

**Comment by TheCoder4eu** [comment]
Thank you bjornbak, I didn't notice it, I think since the release of the last version which introduced deep modularization of css and js something is missing, causing the burger buttons not to work anymore.
I am investigating an I'll keep you posted!

**Comment by TheCoder4eu** [comment]
I found the problem. in fact there was a dependency of the NavBar component from collapse.js that I missed. I am preparing to release a new version with the fix and the Thumbnail component.
