### ISSUE TITLE
Slider is too small in the mobile to operate.

### ISSUE THREAD

**Issue by passgca** [TheCoder4eu/BootsFaces#14]
I am really impressed with BootsFaces.
Any way of controlling the size of the slider . I am unable to use it in a 6 inches mobile phone as it is very very small.

**Comment by TheCoder4eu** [comment]
Hi, nice to hear that you like this project!
Thank you for reporting this, I'll check it on some mobile and investigate for a solution. You have a problem with the handle I suppose...

**Comment by TheCoder4eu** [comment]
I am working on it, in the next release you will have two larger sizes (md and lg) for the handle and the possibility to turn the handle round as well.

**Comment by TheCoder4eu** [comment]
Testing with Bootstrap 3.2.0

**Comment by TheCoder4eu** [comment]
Tests OK.
Documentation updated to include the new features.
