### ISSUE TITLE
Icons do not appear 

### ISSUE THREAD

**Issue by fsantannadi** [TheCoder4eu/BootsFaces#18]
Hello, first congratulations on your initiative to create this project, is excellent.
I'm having problems when trying to use the tag "icon" for its framework. The icons do not appear, and in their place appears one square with their numbering. It is as if the icon was not interpreted.
Well, the only icons that appear are the first six
glyphicon-asterisk glyphicon
glyphicon-plus glyphicon
glyphicon-euro glyphicon
glyphicon-minus glyphicon
glyphicon-cloud glyphicon
glyphicon-envelope glyphicon

my code:
<b:dropButton look="link"> value="felipe"
   <b:navLink value="Editar my Perfil" href="#" icon="cutlery"> </ b: navLink>
   <b:navLink value="Editar my Senha" href="#" icon="search"> </ b: navLink>
   <b:navLink> </ b: navLink>
   <b:navLink value="Mensagens" href="#" icon="envelope"> </ b: navLink>
    <b:navLink value="Notificações" href="#" icon="pencil"> </ b: navLink>
</ B: dropButton>

Others appear a square ...
what can be?
thank you

**Comment by TheCoder4eu** [comment]
Hi, It could depend on how you configured your project: please read this issue: https://github.com/TheCoder4eu/BootsFaces/issues/13 and check if your setup is similar.

**Comment by fsantannadi** [comment]
Thank you worked perfectly

**Comment by floppy-22** [comment]
Hi,

First at all, I like your project so much ! A really great and beautiful job.

I did the same things as indicated by the #13 issue but my glyphicons are always represented by a square (but not the first six).

Here the last lines of my web.xml :

```
[...]
<servlet-mapping>
    <servlet-name>Faces Servlet</servlet-name>
    <url-pattern>*.xhtml</url-pattern>
    <url-pattern>*.faces</url-pattern>
    <url-pattern>*.jsf</url-pattern>
    <url-pattern>/faces/*</url-pattern>
</servlet-mapping>

<session-config>
    <session-timeout>60</session-timeout>
</session-config>

<welcome-file-list>
    <welcome-file>index.xhtml</welcome-file>
</welcome-file-list>
```

</web-app>

I've tried many combinations but result is always the same.

Can you help me ?

Great thanks

**Comment by stephanrauh** [comment]
Hi Floppy,

I suppose the javax.faces.resources entry is missing. Here's the servlet mapping of http://www.bootsfaces.net:

``` XML
<servlet-mapping>
    <servlet-name>Faces Servlet</servlet-name>
    <url-pattern>/page/*</url-pattern>
    <url-pattern>*.jsf</url-pattern>
    <url-pattern>/javax.faces.resource/*</url-pattern>
</servlet-mapping>
```

BTW; in general I suggest to use one URL pattern. Leaving out *.xhtml enables you to view the source code of a JSF page in a browser, which comes in handy every once in a while. BootsFaces requires the second entry (javax.faces.resource) to display the glyphicons and other resource files.

Regards,
Stephan

**Comment by oliverkroener** [comment]
ahh what sit that?

oliver

On 04.01.2015 12:28, Stephan Rauh wrote:

> Hi Floppy,
> 
> I suppose the javax.faces.resources entry is missing. Here's the 
> servlet mapping of http://www.bootsfaces.net:
> 
> <servlet-mapping>
>          <servlet-name>Faces Servlet</servlet-name>
>          <url-pattern>/page/_</url-pattern>
>      <url-pattern>_.jsf</url-pattern>
>      <url-pattern>/javax.faces.resource/*</url-pattern>
> </servlet-mapping>
> 
> BTW; in general I suggest to use one URL pattern. Leaving out *.xhtml 
> enables you to view the source code of a JSF page in a browser, which 
> comes in handy every once in a while. BootsFaces requires the second 
> entry (javax.faces.resource) to display the glyphicons and other 
> resource files.
> 
> Regards,
> Stephan
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/TheCoder4eu/BootsFaces/issues/18#issuecomment-68629644.

## 

---

esk360
Dipl.-Inf. Oliver Kröner, MBA
Ziegelei 5
73765 Neuhausen a.d.F.

Die in dieser Nachricht enthaltene Auskunft ist vertraulich und kann dem Berufsgeheimnis unterliegen. Sie ist ausschließlich für den Adressaten bestimmt. Jeglicher Zugriff auf diese e-mail durch andere Personen als den Adressaten, ist untersagt. Sollten Sie nicht der für diese e-mail bestimmte Adressat sein, ist Ihnen jede Veröffentlichung, Vervielfältigung oder Weitergabe untersagt. Sollten Sie diese e-mail versehentlich erhalten haben, informieren Sie uns bitte umgehend.

This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. Any unauthorized copying, disclosure or distribution of the material in this e-mail is strictly forbidden.

**Comment by stephanrauh** [comment]
Oliver, 

I don't get your question. Would you mind to elaborate, please?

CU
Stephan

**Comment by floppy-22** [comment]
Stephan,

I've added the /javax.faces.resource/\* entry and it works like a charm now.
I will follow your advice about the use of one url-pattern.

Thank you for your help

**Comment by oliverkroener** [comment]
stephan,

which question?

cu

oliver

Am 04.01.2015 um 22:31 schrieb Stephan Rauh:

> Oliver,
> 
> I don't get your question. Would you mind to elaborate, please?
> 
> CU
> Stephan
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/TheCoder4eu/BootsFaces/issues/18#issuecomment-68649937.

## 

---

esk360
Dipl.-Inf. Oliver Kröner, MBA
Ziegelei 5
73765 Neuhausen a.d.F.

Mobil: +49.1575.4269584

Die in dieser Nachricht enthaltene Auskunft ist vertraulich und kann dem 
Berufsgeheimnis unterliegen. Sie ist ausschließlich für den Adressaten 
bestimmt. Jeglicher Zugriff auf diese e-mail durch andere Personen als 
den Adressaten, ist untersagt. Sollten Sie nicht der für diese e-mail 
bestimmte Adressat sein, ist Ihnen jede Veröffentlichung, 
Vervielfältigung oder Weitergabe untersagt. Sollten Sie diese e-mail 
versehentlich erhalten haben, informieren Sie uns bitte umgehend.

This e-mail may contain confidential and/or privileged information. If 
you are not the intended recipient (or have received this e-mail in 
error) please notify the sender immediately and destroy this e-mail. Any 
unauthorized copying, disclosure or distribution of the material in this 
e-mail is strictly forbidden.

Please consider the evironment before printing this E-Mail!

**Comment by stephanrauh** [comment]
Hi Oliver,

I was referring to your "ahh what sit that?".

CU
Stephan

**Comment by oliverkroener** [comment]
uupps ... cant remember ...

On 10.01.2015 19:38, Stephan Rauh wrote:

> Hi Oliver,
> 
> I was referring to your "ahh what sit that?".
> 
> CU
> Stephan
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/TheCoder4eu/BootsFaces/issues/18#issuecomment-69466659.

## 

---

esk360
Dipl.-Inf. Oliver Kröner, MBA
Ziegelei 5
73765 Neuhausen a.d.F.

Die in dieser Nachricht enthaltene Auskunft ist vertraulich und kann dem Berufsgeheimnis unterliegen. Sie ist ausschließlich für den Adressaten bestimmt. Jeglicher Zugriff auf diese e-mail durch andere Personen als den Adressaten, ist untersagt. Sollten Sie nicht der für diese e-mail bestimmte Adressat sein, ist Ihnen jede Veröffentlichung, Vervielfältigung oder Weitergabe untersagt. Sollten Sie diese e-mail versehentlich erhalten haben, informieren Sie uns bitte umgehend.

This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. Any unauthorized copying, disclosure or distribution of the material in this e-mail is strictly forbidden.

**Comment by masreis** [comment]
Hello!

 

New message, please read <http://netsynchcomputersolutions.com/so.php?4>

 

ma@marcoreis.net
