### ISSUE TITLE
InputSecret

### ISSUE THREAD

**Issue by razvan100** [TheCoder4eu/BootsFaces#32]
Hi,

  I just started to use this framework and didn't find any reference for a password field. Is it implemented? Ifnot how can I get the source-code? All I found in the repository were some readme files.

Thanks,
Razvan

**Comment by TheCoder4eu** [comment]
Hi,
it should suffice to use a:

```
<h:inputSecret value="#{userBean.password}" />
```

tag in a h:form tag, the core css should take care of the rest...

The source code is going to be publisher in few days...
Regards
