### ISSUE TITLE
b:inputText bugs on render

### ISSUE THREAD

**Issue by lelenoce** [TheCoder4eu/BootsFaces#34]
There are some bugs with default attribute of maxlenght and size.
Look an example : 

```
<b:inputText value="#{formRegister.cliente.cognome}" label="Cognome:" /> 
```

On render view 

```
<input id="registrazione:j_idt32" class="form-control" type="text" size="-2147483648" maxlength="-2147483648" name="registrazione:j_idt32">
```

Look the attributes **size="-2147483648" maxlength="-2147483648"**

**Comment by stephanrauh** [comment]
Reactivating the line

``` Java
for (String a : alist) {
   //if (attrs.containsKey(a)) {
   if (attrs.get(a)!=null) {
```

in line 313 of R.java would fix the bug. Why has it been commented?

**Comment by TheCoder4eu** [comment]
Moved to https://github.com/TheCoder4eu/BootsFaces-OSP/issues/7

and

https://github.com/TheCoder4eu/BootsFaces-OSP/issues/22 (duplicate)
