### ISSUE TITLE
CSS class seems doesn't works

### ISSUE THREAD

**Issue by guerinorodella** [TheCoder4eu/BootsFaces#35]
Hi everybody!

I just started using Bootsfaces and think this is a great component for JSF, congratullations!

Well.. I'm having a bit of incovenience when I tryed to use my own class inside a button. It seems my CSS class it's not seted up. Here goes my code:

CSS File:

```
.borderless{
   border-radius: 0px;
}
```

And here follows my commandline:

```
<html 
  xmlns="http://www.w3.org/1999/xhtml"
  xmlns:h="http://java.sun.com/jsf/html"
  xmlns:b="http://bootsfaces.net/ui"
  xmlns:f="http://xmlns.jcp.org/jsf/core"
  xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

[...]
    <h:form>
      <b:commandButton class="borderless" value="No border" >
   </h:form>
[...]
```

It doesn't works for tag `<b:inputText>`too. What I'm doing wrong?
Thanks.

**Comment by TheCoder4eu** [comment]
Hi, it's nice to hear you like this project.

I moved this issue here https://github.com/TheCoder4eu/BootsFaces-OSP/issues/24 on the new repository.
