### ISSUE TITLE
Bug on b:panel collapsible=true

### ISSUE THREAD

**Issue by ghost** [TheCoder4eu/BootsFaces#38]
regarding bootsfaces 0.7.0 from maven central repository

on using tag from the collapsible=true configuration. This comes up by myfaces in a warning: HTML nesting warning on closing a: element h4 rendered by component...

Solution: fix render closing a tag only when collapsible != false

**Comment by TheCoder4eu** [comment]
I close this one, already taken care here:
https://github.com/TheCoder4eu/BootsFaces-OSP/issues/126
