### ISSUE TITLE
DatePicker Disabled

### ISSUE THREAD

**Issue by andrespineda23** [TheCoder4eu/BootsFaces#39]
how to change the disabled of the date picker? Thanks.

**Comment by TheCoder4eu** [comment]
Hi, looks like you filed the issue to the wrong project, we changed repository, the right one is
https://github.com/TheCoder4eu/BootsFaces-OSP

I also did not understand well what you are trying to obtain, can you elaborate when you open the issue on the other repository?
Thanks!
