### ISSUE TITLE
Warning: unable to save dynamic action

### ISSUE THREAD

**Issue by rpinquie** [TheCoder4eu/BootsFaces#47]
Hi,

I am getting a bunch of warnings as the one hereunder. Does anyone know why ?

mars 08, 2016 6:59:44 PM com.sun.faces.application.view.FaceletPartialStateManagementStrategy saveDynamicActions
AVERTISSEMENT: Unable to save dynamic action with clientId 'j_id29' because the UIComponent cannot be found

**Comment by stephanrauh** [comment]
Yes. It's an OmniFaces bug (or rather: nuisance) that has been fixed in the meantime. Update to OmniFaces 2.2, and you should get rid of the warning.

BTW, this is the wrong project. Please open your issue in the BootsFaces-OSP project. Thanks!

**Comment by rpinquie** [comment]
close
